FROM fastapi-test-base:latest

WORKDIR /app

COPY ./server.py ./server.py
COPY ./server_launch.py ./server_launch.py
COPY ./tests.py ./tests.py
COPY ./tests_launch.py ./tests_launch.py
COPY ./mlflow_utils.py ./mlflow_utils.py

# COPY ./requirements-test.txt ./requirements.txt

ENV ENV_MODE=TESTS

# RUN pip install -r requirements.txt

# CMD ["python", "tests_launch.py"]