{
 "title": "FastAPI Accidents",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Pods en panne",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum_over_time(kube_pod_container_status_waiting_reason{job=\"kube-state-metrics\",namespace=~\"projet-mlops\",reason=~\"CrashLoopBackOff|Error\"}[1m]) >= 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requêtes par endpoint",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(rate(nb_of_requests_total[5m])) by (exported_endpoint)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Erreurs http",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "avg(rate(nb_of_errors_total[1m])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temps d'exécution des prédictions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "avg(rate(requests_duration_sum[5m])) by (exported_endpoint) / avg(rate(requests_duration_count[5m])) by (exported_endpoint)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}